image: docker:19.03
services:
  - name: docker:19.03-dind
    command: ["--insecure-registry=192.168.1.4:5000"]
variables:
#  DOCKER_HOST: tcp://localhost:2375
  DOCKER_DRIVER: overlay2
  KUBECONFIG: /etc/deploy/config
  MAVEN_OPTS: "-Dmaven.repo.local=/opt/cache/.m2/repository"

stages:
  - package
  - docker_build
  - deploy_k8s

mvn_build_job:
  image: 192.168.1.4:5000/maven:3.6.2-ibmjava-8-alpine
  stage: package
  tags:
    - cloud-runner
  script:
    - mvn package -B -DskipTests
    - echo $CI_PROJECT_DIR
    - cp target/cloud-register.jar /workspace
docker_build_job:
  stage: docker_build
  tags:
    - cloud-runner
  only:
    - master
  script:
    # - docker info
    - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD 192.168.1.4:5000
    - mkdir target
    - cp /workspace/cloud-register.jar target/cloud-register.jar
    - docker build -t 192.168.1.4:5000/cloud-register:$CI_PIPELINE_ID .
    - docker push 192.168.1.4:5000/cloud-register:$CI_PIPELINE_ID
deploy_k8s_job:
  stage: deploy_k8s
  tags:
    - cloud-runner
  script:
    - mkdir -p /etc/deploy/
    - echo $kube_config |base64 -d > $KUBECONFIG
    - sed -i "s/IMAGE_TAG/$CI_PIPELINE_ID/g" deployment.yaml
    - cat deployment.yaml
    - kubectl apply -f deployment.yaml
