image: docker:19.03
services:
  - name: docker:19.03-dind
    command: ["–-privileged=true --insecure-registry=192.168.1.4:5000"]
variables:
  DOCKER_DRIVER: overlay2
  KUBECONFIG: /etc/deploy/config
  MAVEN_OPTS: "-Djava.awt.headless=true -Dmaven.repo.local=/root/.m2/repository"

stages:
  - package
  - docker_build
  - deploy_k8s

mvn_build_job:
  image: 192.168.1.4:5000/maven:3.6.2-ibmjava-8-alpine
  stage: package
  tags:
    - cloud-runner
  script:
    - mvn package -B -DskipTests
    - cp target/*.jar /opt/cache
docker_build_job:
  stage: docker_build
  tags:
    - cloud-runner
  only:
    - master
  script:
    - mkdir target && cp /opt/cache/cloud-register.jar target/
    - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD 192.168.1.4:5000
    - docker build -t 192.168.1.4:5000/cloud-register:$CI_PIPELINE_ID .
    - docker push 192.168.1.4:5000/cloud-register:$CI_PIPELINE_ID
deploy_k8s_job:
  image: 192.168.1.4:5000/kubectl:v1.13.0
  stage: deploy_k8s
  tags:
    - cloud-runner
  script: 
    - "mkdir $HOME/.kube && echo $kube_config |base64 -d > $HOME/.kube/config;"
    - "set runner = kubectl get pods -n kube-system | awk '{if($1~/cloud-gateway/) print $1}';"
    - if [ -n $runner ]; then
        line='s/IMAGE_TAG/$CI_PIPELINE_ID/g'; sed -i "$line" deployment.yaml;
        kubectl apply -f deployment.yaml;
      else
        kubectl rolling-update cloud-gateway --image=192.168.1.4:5000/cloud-gateway:$CI_PIPELINE_ID;
      fi
