# apiVersion: extensions/v1beta1
# kind: Deployment
# metadata:
#   name: cloud-register
# spec:
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: cloud-register
#     spec:
#       containers:
#       - name: cloud-register
#         image: 192.168.1.4:5000/cloud-register:IMAGE_TAG
#         imagePullPolicy: Always
#         ports:
#         - containerPort: 1111
#           name: cloud-register

# ---
apiVersion: v1
kind: ReplicationController
metadata:
  name: cloud-register
  labels:
    name: cloud-register
spec:
  replicas: 1
  selector:
    name: cloud-register
  template:
    metadata:
      labels: 
        name: cloud-register
    spec:
      containers:
      - name: cloud-register
        image: 192.168.1.4:5000/cloud-register:IMAGE_TAG
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: Asia/Shanghai
        - name: INIT
          value: "false"
        ports:
        - containerPort: 1111
          name: cloud-register

---
apiVersion: v1
kind: Service
metadata:
  name: register-svc
  labels: 
    name: register-svc
spec:
  type: NodePort
  ports:
  - port: 1111
    protocol: TCP
    targetPort: cloud-register
    nodePort: 1111
  selector:
    name: cloud-register