apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloud-register
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cloud-register
    spec:
      containers:
      - name: cloud-register
        image: 192.168.1.4:5000/cloud-register:IMAGE_TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 1111